AWSTemplateFormatVersion: "2010-09-09"
Description: APIGW NLB ALB ECS cluster and service
Parameters:
  pDesiredCount:
    Type: String
  pTGroup:
    Type: String
  pTaskSGroup:
    Type: String
  pSubnetIds:
    Type: List<String>
  pALBArn:
    Type: String
  pImageUri:
    Type: String
Resources:
  ExecRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/service-role/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/service-role/'
      Policies:
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 'arn:aws:logs:*:*:log-group:*:*'
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !GetAtt Cluster.Arn
      DesiredCount: !Ref pDesiredCount
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: springboot_native_container
          ContainerPort: 8080
          TargetGroupArn: !Ref pTGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref pTaskSGroup
          Subnets: !Ref pSubnetIds
      TaskDefinition: !Ref Task
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: springboot_native
      ExecutionRoleArn: !GetAtt ExecRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      Cpu: 1024
      Memory: 2048
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: springboot_native_container
          Image: !Ref pImageUri
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /aws/ecs/springboot_native
              awslogs-region: us-east-1
              awslogs-stream-prefix: ecs
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
Outputs:
  outCluster:
    Value: !Ref Cluster
  outService:
    Value: !Ref Service
  outTask:
    Value: !Ref Task